export enum Categoria {
    ELETTRONICA = "ELETTRONICA",
	INFORMATICA = "INFORMATICA",
	TELEFONIA = "TELEFONIA",
	CASA_E_CUCINA = "CASA E CUCINA",
	ABBIGLIAMENTO = "ABBIGLIAMENTO",
	CALZATURE = "CALZATURE",
	SPORT_E_FITNESS = "SPORT E FITNESS",
	BELLEZZA_E_CURA_DELLA_PERSONA = "BELLEZZA E CURA DELLA PERSONA",
	GIOCATTOLI = "GIOCATTOLI",
	ALIMENTARI = "ALIMENTARI"
}

export type RoleType = Categoria;