export enum ComboTables {
	REGIONI = "REGIONI",
	PROVINCIE = "PROVINCIE",
	COMUNI = "COMUNI",
	FORMA_GIURIDICA = "FORMA_GIURIDICA",
	INSTALLAZIONE = "INSTALLAZIONE",
	PRODUTTORE = "PRODUTTORE",
	TIPOLOGIA = "TIPOLOGIA",
	TIPO_UTENTE = "TIPO_UTENTE",
	STATO = "STATO",
}

export type ComboTable = ComboTables;
